### ISSUE TITLE
On Smaller Screen, Navbar  border get Overlapped

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/RSNewWebUI#17]
# Review
![issueretro](https://user-images.githubusercontent.com/64456168/111144508-2914d680-85ad-11eb-87a6-ebc23252e8f0.JPG)

**Comment by Kumaravinash9** [comment]
@csoler @G10h4ck  I want to work on this.

**Comment by csoler** [comment]
Hi. The web interface has changed quite a bit since this view above. Make sure to use the new one! 
There's a call by Freifunk to work on the topic of improving the web interface in the context of Google Summer of Code 2021. If you're a student, see if you can apply!

**Comment by Kumaravinash9** [comment]
Hi @csoler I am student and looking forward to take part in GSOC 21 .Really looking forward to get guidance .

**Comment by csoler** [comment]
Take a look here: https://github.com/RetroShare/RSNewWebUI. The README explains how to compile Retroshare so as to run the web interface. The compilation options should be "rs_jsonapi rs_webui debug" (rs_webui seems to be missing in the webpage above). Make sure you can run it.
In order to get help, the best way is to add the Retroshare Tor dev node to your friends. I'll PM you the key. You need to have Tor run on your system to connect to it.

**Comment by csoler** [comment]
... ah and you need to provide some contact email for that on github ;-)

**Comment by Kumaravinash9** [comment]
Thanks @csoler. This is my Email Id : avinashkumar.met18@itbhu.ac.in

**Comment by Kumaravinash9** [comment]
@csoler Actually I followed the Readme to setup the developement environment . But i am facing some problem  (I am using Windows)
 - After installing retroshare 
 - I didnot see any option  of JSON API  in Preference section:
 
![problem](https://user-images.githubusercontent.com/64456168/111157058-70569380-85bc-11eb-8d1e-d715f01f32bb.JPG)

**Please help**

**Comment by defnax** [comment]
> @csoler Actually I followed the Readme to setup the developement environment . But i am facing some problem (I am using Windows)
> 
> * After installing retroshare
> * I didnot see any option  of JSON API  in Preference section:
> 
> ![problem](https://user-images.githubusercontent.com/64456168/111157058-70569380-85bc-11eb-8d1e-d715f01f32bb.JPG)
> 
> **Please help**

You need to use a new RetroShare 0.6.6 with JSON api & Webui enabled

**Comment by Kumaravinash9** [comment]
@G10h4ck Can I update the readme so that the new developer has no problem setting up the development environment.

**Comment by defnax** [comment]
Here are some infos for the webui:
https://github.com/RetroShare/RetroShare/issues/2160

**Comment by Kumaravinash9** [comment]
Thanks @defnax

**Comment by Kumaravinash9** [comment]
@defnax 
After enable the JSON API :
![issuedynax](https://user-images.githubusercontent.com/64456168/111215099-c0534b80-85f8-11eb-804b-bba8e575a322.JPG)
# Check this
![major_issue](https://user-images.githubusercontent.com/64456168/111215315-07414100-85f9-11eb-9810-a47546a832a8.JPG)

**please help @defnax**

**Comment by defnax** [comment]
as i said you need windows developer build, official release no webui (still is unfinished).

**Comment by Kumaravinash9** [comment]
@csoler  @defnax  can I update the Readme .

**Comment by csoler** [comment]
Of course. Make a pull request.

**Comment by Kumaravinash9** [comment]
@csoler @defnax 
# Why is it not working
![issueconfig](https://user-images.githubusercontent.com/64456168/111282610-3214af00-8664-11eb-9dad-c5b375482949.JPG)

**Comment by defnax** [comment]
As i said is unfinished, join to rs dev network and ask the devs/testers on RetroShare.
Im not a web dev. You know now to start the webui.

**Comment by Kumaravinash9** [comment]
Hello @csoler @defnax   , i dropped my message on this  Retroshare Tor dev node about my issue  but didnot get any help.

**Comment by csoler** [comment]
hi. I dont think you ever connected to the dev Tor node. Your last contact here is from March 15, which is when I added your key in the first place.

**Comment by Kumaravinash9** [comment]
@csoler , i am in the group 
![recent](https://user-images.githubusercontent.com/64456168/112213553-346aa080-8c44-11eb-9c39-54274ff31cbd.JPG)

**Comment by Kumaravinash9** [comment]
Here is my key :

ABCzSYCT3kEMgccHuNcgK6RZAxRX39zcYGPBqL4hHsY125UBEW6TlQEIS3VtYXJBdmmTBgGJqMDBgpIG8zvWdcGCBANZmb8=

**Comment by csoler** [comment]
Your key is already added (unless you changed it since last week?)

**Comment by Kumaravinash9** [comment]
It downloaded newer version of retroshare that was recommended by @defnax

**Comment by csoler** [comment]
ok. I added the new one.

**Comment by Kumaravinash9** [comment]
@csoler , I have updated readme and created a PR request for it .

**Comment by csoler** [comment]
merged it. You're still not connected. Are you running Tor on your machine?

**Comment by Kumaravinash9** [comment]
Yes @csoler , I am connected  

![chevk](https://user-images.githubusercontent.com/64456168/112216135-2bc79980-8c47-11eb-8572-3b9c2058fdcf.JPG)

**Comment by csoler** [comment]
No you're not. You just added the dev Tor node as friend. That means you accept connectioons with this node. But currently you're not connected. When you are, the node should be listed in bold green, and the bottom of the window should show 1/1 instead of 0/1 (see the tooltip).
That explains why you sent messages but they were never received.

**Comment by Kumaravinash9** [comment]
@csoler then how can i connect

**Comment by csoler** [comment]
normally RS should do it by itself. If it doesn't it means you probably do not run Tor on your machine, or your router/ISP filters it. See preferences->network->hidden service configuration->outgoing. There's a "Tor outgoing Okay" LED here that should be green. If not, it means you're not running Tor.

**Comment by Kumaravinash9** [comment]
@csoler  It is not green .

**Comment by csoler** [comment]
what's your system?

**Comment by Kumaravinash9** [comment]
@csoler  Windows 10

**Comment by csoler** [comment]
I don't know how to run Tor on windows. Try to launch a Tor browser. It may do the job, but on windows you never know.

**Comment by Kumaravinash9** [comment]
@csoler can you please guide me how to Launch Tor browser

**Comment by csoler** [comment]
https://www.torproject.org/download/. Just launch the .exe that you'll get.

**Comment by Kumaravinash9** [comment]
Thanks @csoler and  actually , I was busy in university exam. That' why I made a late PR request.

**Comment by csoler** [comment]
well, that wasn't a very complicated PR ;-)

**Comment by Kumaravinash9** [comment]
@csoler , i have installed Tor browser. So what to do next

**Comment by csoler** [comment]
launch it. Then check that RS can see Tor (green LED)

**Comment by Kumaravinash9** [comment]
I have launched Tor node browser but it's not green.

**Comment by csoler** [comment]
try to set the proxy port in the RS settings (same place) to 9150

**Comment by csoler** [comment]
this is because TorBrowser uses 9150 instead of the default (9050), so you have to tell Retroshare to use this one as well.

**Comment by Kumaravinash9** [comment]
@csoler , check this 
![saveasCheck](https://user-images.githubusercontent.com/64456168/112220351-2b7dcd00-8c4c-11eb-9f03-5087e4153e93.JPG)

**Comment by csoler** [comment]
seems to me ok! So normally RS should be able to connect now. It tries less and less often, so if you started it long ago, it will quick things up to right-click on the dev node and select "attempt to connect"

**Comment by csoler** [comment]
You should probably not use the same port for I2P and Tor though. Just leave 9050 for I2P since you dont use it.

**Comment by Kumaravinash9** [comment]
> You should probably not use the same port for I2P and Tor though. Just leave 9050 for I2P since you dont use it.

I changed it

**Comment by Kumaravinash9** [comment]
# Still facing problem 
![eror](https://user-images.githubusercontent.com/64456168/112221972-1efa7400-8c4e-11eb-9e95-b70f2a9b43ce.JPG)

**Comment by csoler** [comment]
why is it still using 9050 instead of 9150?? try to restart RS?

**Comment by Kumaravinash9** [comment]
Thanks a lot  @csoler , now i am connected 
![connected](https://user-images.githubusercontent.com/64456168/112222787-06d72480-8c4f-11eb-8de2-4d2187750655.JPG)

**Comment by csoler** [comment]
Congrats. Took some time, but your situation is the most complicated one: clear node to Tor node on windows ;-)

**Comment by Kumaravinash9** [comment]
Finally connected :-)

**Comment by rottencandy** [comment]
Worth noting that the windows build script is not up to date with the bash script, and needs to be updated.
It will probably not build the webui properly, I created an issue for this https://github.com/RetroShare/RSNewWebUI/issues/19

In the meantime, you could use something like Cygwin or WSL to build using the bash script.

**Comment by Kumaravinash9** [comment]
@rottencandy please can you describe me more how to use Cygwin or WSL for building the script

**Comment by Kumaravinash9** [comment]
> @rottencandy please can you describe me more how to use Cygwin or WSL for building the script

but i built it using Cygwin but it didn't work

**Comment by rottencandy** [comment]
Maybe try WSL: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by rottencandy** [comment]
> i built it using Cygwin but it didn't work

But which step did not work? Were you able to run the bash script?

**Comment by Kumaravinash9** [comment]
> @csoler @defnax
> 
> # Why is it not working
> ![issueconfig](https://user-images.githubusercontent.com/64456168/111282610-3214af00-8664-11eb-9dad-c5b375482949.JPG)

Actually when i try to open web interface then it shows something like this. May be some problem is coming in detecting files

**Comment by rottencandy** [comment]
Is that the webui you get after running the bash script or the windows script? Can you try opening the `index.html` file directly and see what you get?

**Comment by Kumaravinash9** [comment]
Yes @rottencandy

**Comment by rottencandy** [comment]
No, I meant which script did you use to get that : p

**Comment by Kumaravinash9** [comment]
sh build.sh

**Comment by Kumaravinash9** [comment]
@rottencandy  Chrome debugging  console
![pblm](https://user-images.githubusercontent.com/64456168/112367874-7bb66700-8d00-11eb-8fae-6e14d4400f10.JPG)

**Comment by rottencandy** [comment]
Does it work when you open `index.html` directly?

(You should ask this in the dev chatroom, you'd get much faster response there)

**Comment by Kumaravinash9** [comment]
doesn't work . And yesterday I talked with @cyril regarding this . He also donot know how to resolve this.

**Comment by rottencandy** [comment]
Okay, looks like chrome has trouble reading the font files. Apart from that, do the other tabs load? Looks like the fetch calls are working based on your previous screenshot.

**Comment by hunbernd** [comment]
If you have msys2 installed, start the migw64.exe, and you can run the build.sh from there.
Then you have to copy the generated files into the folder retrosharefolder\webui, and let the internal webserver serve them.

If you have more questions about building or running RS on windows, feel free to contact me over RS:
anmo (2d7fdbc8d6894c131a7588fd05c816fb)

**Comment by csoler** [comment]
Maybe I forgot to clear this up: you shouldn't load the .html directly in your browser! Otherwise, yes, internal resources will not have the right path. You need to access http://127.0.0.1:9092/index.html once retroshare is running.

**Comment by csoler** [comment]
And if you do, try to keep the default port. Maybe there's still explicit mentions of that port (9092) in the code, so some files cannot be found with your custom port?

**Comment by Kumaravinash9** [comment]
@csoler  Yes , i can see in login.js file where it's is defined that `window.location.protocol` starts with `file`: then it try to connect server at 9092 port.  

![protocal](https://user-images.githubusercontent.com/64456168/112452564-c4136a80-8d7c-11eb-83b3-c38d2bfa0dbb.JPG)

**Comment by Kumaravinash9** [comment]
@csoler @hunbernd  
My json Api config
![jsonconfig](https://user-images.githubusercontent.com/64456168/112453303-91b63d00-8d7d-11eb-81b6-91ae98734a71.JPG)
 Web Interface config 
![webinterface-config](https://user-images.githubusercontent.com/64456168/112453476-c0ccae80-8d7d-11eb-8b62-28ee68d04312.JPG)
But still not Working .

**Comment by Kumaravinash9** [comment]
> If you have msys2 installed, start the migw64.exe, and you can run the build.sh from there.
> Then you have to copy the generated files into the folder retrosharefolder\webui, and let the internal webserver serve them.
> 
> If you have more questions about building or running RS on windows, feel free to contact me over RS:
> anmo (2d7fdbc8d6894c131a7588fd05c816fb)

@hunbernd  Actually i have tried but it's not working

**Comment by csoler** [comment]
Look at your jsonapi port, and compare to default webui port....

**Comment by Kumaravinash9** [comment]
> @csoler @hunbernd
> My json Api config
> ![jsonconfig](https://user-images.githubusercontent.com/64456168/112453303-91b63d00-8d7d-11eb-81b6-91ae98734a71.JPG)
> Web Interface config
> ![webinterface-config](https://user-images.githubusercontent.com/64456168/112453476-c0ccae80-8d7d-11eb-8b62-28ee68d04312.JPG)
> But still not Working .

@csoler , i have set it to 9092 port

**Comment by csoler** [comment]
it looks like 9020 in the image above.

**Comment by Kumaravinash9** [comment]
@csoler sorry

**Comment by Kumaravinash9** [comment]
@csoler i have set it to 9092 but still not working

![setit](https://user-images.githubusercontent.com/64456168/112458024-59652d80-8d82-11eb-81fb-f94bc50e31f3.JPG)

**Comment by csoler** [comment]
did you click on "apply settings" ?

**Comment by Kumaravinash9** [comment]
yes

> did you click on "apply settings" ?

yes

**Comment by hunbernd** [comment]
This should fix the woff file problems:
https://github.com/RetroShare/RetroShare/pull/2393

**Comment by Kumaravinash9** [comment]
thanks a lot  @hunbernd 
now, i can able to use web interface 
![Capture](https://user-images.githubusercontent.com/64456168/112668834-f7412100-8e84-11eb-86a2-57ea969d59ec.JPG)

**Comment by G10h4ck** [comment]
Great to see so much activity on this topic! Sorry being late but I am exploring how to implement perceptual indexing and search (similar to https://en.wikipedia.org/wiki/Acoustic_fingerprint but also for images and videos) on RetroShare right now and it keep my mind very busy!

**Comment by Kumaravinash9** [comment]
no problem @G10h4ck  . My  issue has solved . @csoler @rottencandy  @hunbernd @defnax @cyril  these are great people  who helped me a lot to get over this issue.
